---
title: "3D visualization"
format: revealjs
editor: visual
---

```{r}
#| label: Load libraries
#| warning: false
#| message: false
#| echo: false
library(ggplot2)
library(tidyverse)
library(esquisse)
library(stringr)
library(gridExtra)
library(plotly)
```

```{r}
#| echo: false
AMM12_1<-read.csv("C:/Users/SamXi/OneDrive/Desktop/consulting/entorhinal_cortex/AMM12_4DetectionsL2.csv",header=TRUE)
AMM20_1<-read.csv("C:/Users/SamXi/OneDrive/Desktop/consulting/entorhinal_cortex/AMM20_5DetectionsL2.csv",header=TRUE)
AMM12_2<-read.csv("C:/Users/SamXi/OneDrive/Desktop/consulting/entorhinal_cortex/AMM12_5DetectionsL2.csv",header=TRUE)

AMM12_1 <- AMM12_1[c("Name","Cell..Opal.520.mean","Cell..Opal.570.mean", "Cell..Opal.620.mean", "Cell..Opal.690.mean" , "Distance.to.annotation.with.line.µm")]
colnames(AMM12_1) <- c("Name", "MFI520", "MFI570", "MFI620", "MFI690", "dist")


AMM12_1$'IND520' <- grepl("Opal 520", AMM12_1$Name)
AMM12_1$'IND570' <- grepl("Opal 570", AMM12_1$Name)
AMM12_1$'IND620' <- grepl("Opal 620", AMM12_1$Name)
AMM12_1$'IND690' <- grepl("Opal 690", AMM12_1$Name)

AMM12_1 <- AMM12_1[,-1]

AMM12_1 <- filter(AMM12_1, MFI520 != 0 & MFI570 != 0 & MFI620 != 0 & MFI690 != 0)

log_FI <- log(AMM12_1[,1:5])


fig_all <- plot_ly(log_FI, x = ~MFI570, y = ~MFI620, z = ~MFI690, marker = list(color = ~MFI520, colorscale = "Rainbow", showscale = TRUE, size = 3))
fig_all <- fig_all %>% add_markers()
fig_all <- fig_all %>% layout(title = "570 vs. 620 vs 690,in layer 1",
                              scene = list(xaxis = list(title = '570'),
                                           yaxis = list(title = '620'),
                                           zaxis = list(title = '690')))



log_FI <- log(filter(AMM12_1, IND520 == T & MFI520 < quantile(AMM12_1$MFI520, 0.95) ))
fig_520 <- plot_ly(log_FI, x = ~MFI570, y = ~MFI620, z = ~MFI690, marker = list(color = ~MFI520, colorscale = "Rainbow", showscale = TRUE, size = 3))
fig_520 <- fig_520 %>% add_markers()
fig_520 <- fig_520 %>% layout(title = "520=T,570 vs. 620 vs 690, in layer 1",
                              scene = list(xaxis = list(title = '570'),
                                           yaxis = list(title = '620'),
                                           zaxis = list(title = '690')))



log_FI <- log(filter(AMM12_1,  MFI520 < quantile(AMM12_1$MFI520, 0.95) & dist > quantile(AMM12_1$dist, 0.05)))
fig_dist <- plot_ly(log_FI, x = ~MFI520, y = ~MFI570, z = ~MFI690, marker = list(color = ~dist, colorscale = "Rainbow", showscale = TRUE, size = 3))
fig_dist <- fig_dist %>% add_markers()
fig_dist <- fig_dist %>% layout(title = "520=T, 520 vs. 570 vs 690, in layer 1",
                                scene = list(xaxis = list(title = '520'), 
                                             yaxis = list(title = '570'), 
                                             zaxis = list(title = '690')))

## Another layer
AMM12_2 <- AMM12_2[c("Name","Cell..Opal.520.mean","Cell..Opal.570.mean", "Cell..Opal.620.mean", "Cell..Opal.690.mean" , "Distance.to.annotation.with.line.µm")]
colnames(AMM12_2) <- c("Name", "MFI520", "MFI570", "MFI620", "MFI690", "dist")


AMM12_2$'IND520' <- grepl("Opal 520", AMM12_2$Name)
AMM12_2$'IND570' <- grepl("Opal 570", AMM12_2$Name)
AMM12_2$'IND620' <- grepl("Opal 620", AMM12_2$Name)
AMM12_2$'IND690' <- grepl("Opal 690", AMM12_2$Name)

AMM12_2 <- AMM12_2[,-1]

AMM12_2 <- filter(AMM12_2, MFI520 != 0 & MFI570 != 0 & MFI620 != 0 & MFI690 != 0)

log_FI2 <- log(AMM12_2[,1:5])


fig2_all <- plot_ly(log_FI2, x = ~MFI570, y = ~MFI620, z = ~MFI690, marker = list(color = ~MFI520, colorscale = "Rainbow", showscale = TRUE, size = 3))
fig2_all <- fig2_all %>% add_markers()
fig2_all <- fig2_all %>% layout(title = "570 vs. 620 vs 690,in layer 2",
                                scene = list(xaxis = list(title = '570'),
                                           yaxis = list(title = '620'),
                                           zaxis = list(title = '690')))




log_FI2 <- log(filter(AMM12_2, IND520 == T & MFI520 < quantile(AMM12_2$MFI520, 0.95) ))
fig2_520 <- plot_ly(log_FI2, x = ~MFI570, y = ~MFI620, z = ~MFI690, marker = list(color = ~MFI520, colorscale = "Rainbow", showscale = TRUE, size = 3))
fig2_520 <- fig2_520 %>% add_markers()
fig2_520 <- fig2_520 %>% layout(title = "520=T,570 vs. 620 vs 690, in layer 2",
                                scene = list(xaxis = list(title = '570'),
                                           yaxis = list(title = '620'),
                                           zaxis = list(title = '690')))



log_FI2 <- log(filter(AMM12_2,  MFI520 < quantile(AMM12_2$MFI520, 0.95) & dist > quantile(AMM12_2$dist, 0.05)))
fig2_dist <- plot_ly(log_FI2, x = ~MFI520, y = ~MFI570, z = ~MFI690, marker = list(color = ~dist, colorscale = "Rainbow", showscale = TRUE, size = 3))
fig2_dist <- fig2_dist %>% add_markers()
fig2_dist <- fig2_dist %>% layout(title = "520=T,520 vs. 570 vs 690, in layer 2",
                                  scene = list(xaxis = list(title = '520'), 
                                               yaxis = list(title = '570'),
                                               zaxis = list(title = '690')))


## The third layer
AMM20_1 <- AMM20_1[c("Name","Cell..Opal.520.mean","Cell..Opal.570.mean", "Cell..Opal.620.mean", "Cell..Opal.690.mean" , "Distance.to.annotation.with.line.µm")]
colnames(AMM20_1) <- c("Name", "MFI520", "MFI570", "MFI620", "MFI690", "dist")


AMM20_1$'IND520' <- grepl("Opal 520", AMM20_1$Name)
AMM20_1$'IND570' <- grepl("Opal 570", AMM20_1$Name)
AMM20_1$'IND620' <- grepl("Opal 620", AMM20_1$Name)
AMM20_1$'IND690' <- grepl("Opal 690", AMM20_1$Name)

AMM20_1 <- AMM20_1[,-1]

AMM20_1 <- filter(AMM20_1, MFI520 != 0 & MFI570 != 0 & MFI620 != 0 & MFI690 != 0)

log_FI3 <- log(AMM20_1[,1:5])


fig3_all <- plot_ly(log_FI3, x = ~MFI570, y = ~MFI620, z = ~MFI690, marker = list(color = ~MFI520, colorscale = "Rainbow", showscale = TRUE, size = 3))
fig3_all <- fig3_all %>% add_markers()
fig3_all <- fig3_all %>% layout(title = "570 vs. 620 vs 690,in layer 3",
                                scene = list(xaxis = list(title = '570'),
                                             yaxis = list(title = '620'),
                                             zaxis = list(title = '690')))




log_FI3 <- log(filter(AMM20_1, IND520 == T & MFI520 < quantile(AMM20_1$MFI520, 0.95) ))
fig3_520 <- plot_ly(log_FI3, x = ~MFI570, y = ~MFI620, z = ~MFI690, marker = list(color = ~MFI520, colorscale = "Rainbow", showscale = TRUE, size = 3))
fig3_520 <- fig3_520 %>% add_markers()
fig3_520 <- fig3_520 %>% layout(title = "520=T,570 vs. 620 vs 690, in layer 3",
                                scene = list(xaxis = list(title = '570'),
                                             yaxis = list(title = '620'),
                                             zaxis = list(title = '690')))



log_FI3 <- log(filter(AMM20_1,  MFI520 < quantile(AMM20_1$MFI520, 0.95) & dist > quantile(AMM20_1$dist, 0.05)))
fig3_dist <- plot_ly(log_FI3, x = ~MFI520, y = ~MFI570, z = ~MFI690, marker = list(color = ~dist, colorscale = "Rainbow", showscale = TRUE, size = 3))
fig3_dist <- fig3_dist %>% add_markers()
fig3_dist <- fig3_dist %>% layout(title = "520=T, 520 vs. 570 vs 690, in layer 3",
                                  scene = list(xaxis = list(title = '520'),
                                               yaxis = list(title = '570'),
                                               zaxis = list(title = '690')))

```
# p1
```{r}
fig_all
```
# p2
```{r}
fig2_all
```
# p3
```{r}
fig3_all
```
# p4
```{r}
fig_520
```
# p5
```{r}
fig2_520
```
# p6
```{r}
fig3_520
```
# p7
```{r}
fig_dist
```
# p8
```{r}
fig2_dist
```
# p9
```{r}
fig3_dist
```

